FROM python:3.10-slim

ENV TZ=America/Sao_Paulo

RUN apt-get update && apt-get install -y netcat-traditional


WORKDIR /app

COPY . /app/

RUN pip install --upgrade pip

RUN pip install --no-cache-dir -r requirements.txt
COPY wait-for-kafka.sh /wait-for-kafka.sh

RUN chmod +x /wait-for-kafka.sh

# Altera o comando de inicialização para esperar o Kafka
CMD [ "python", "produtor.py"]