DECLARE @valor1 INT = 10;
DECLARE @valor2 int = 5;
DECLARE @valor3 FLOAT = 34;
DECLARE @valor4 FLOAT = 7;

DECLARE @SOMA INT;
DECLARE @SUBTRACAO INT;
DECLARE @MULTIPLICACAO INT;
DECLARE @DIVISAO FLOAT;

SET @SOMA =  @valor1 + @valor2;
PRINT @SOMA

SET @SUBTRACAO =  @valor3 + @valor4;
PRINT @SUBTRACAO


SET @MULTIPLICACAO = @valor1  + @valor4
PRINT @MULTIPLICACAO

SET @DIVISAO = @valor3 / @valor4
PRINT ROUND(@DIVISAO , 2)